package com.hbo.hcl.mind;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Venkatesh.Sampath
 */
public class GettingTagPanel extends javax.swing.JFrame {

    /**
     * Creates new form GettingTagPanel
     */
    public GettingTagPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JTabbedPane();
        NotificationPanel = new javax.swing.JPanel();
        scheduleTagJL = new javax.swing.JLabel();
        schedulerTagJT = new javax.swing.JTextField();
        PTSOTagJL = new javax.swing.JLabel();
        PTSOTagJT = new javax.swing.JTextField();
        photoTagJT = new javax.swing.JTextField();
        P2TagJT = new javax.swing.JTextField();
        previewTagJT = new javax.swing.JTextField();
        blurbTagJT = new javax.swing.JTextField();
        photoTagJL = new javax.swing.JLabel();
        P2TagJL = new javax.swing.JLabel();
        previewTagJL = new javax.swing.JLabel();
        blurbTagJL = new javax.swing.JLabel();
        TagHeadingJL = new javax.swing.JLabel();
        GenerateSQLJB = new javax.swing.JButton();
        ResetFormJB = new javax.swing.JButton();
        PermissionPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setToolTipText("");
        MainPanel.setAutoscrolls(true);
        MainPanel.setName("PermissionTab"); // NOI18N
        MainPanel.setPreferredSize(new java.awt.Dimension(400, 400));

        NotificationPanel.setName("NotificationPanel"); // NOI18N

        scheduleTagJL.setText("Scheduler");

        schedulerTagJT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schedulerTagJTActionPerformed(evt);
            }
        });

        PTSOTagJL.setText("PTSO");

        photoTagJL.setText("Photo");

        P2TagJL.setText("P2");

        previewTagJL.setText("Preview");

        blurbTagJL.setText("BLurb");

        TagHeadingJL.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TagHeadingJL.setForeground(new java.awt.Color(153, 0, 153));
        TagHeadingJL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TagHeadingJL.setText("Tag Tkeys ");
        TagHeadingJL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        GenerateSQLJB.setText("Generate SQL");

        ResetFormJB.setText("Reset Form");
        ResetFormJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetFormJBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NotificationPanelLayout = new javax.swing.GroupLayout(NotificationPanel);
        NotificationPanel.setLayout(NotificationPanelLayout);
        NotificationPanelLayout.setHorizontalGroup(
            NotificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NotificationPanelLayout.createSequentialGroup()
                .addGroup(NotificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NotificationPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(NotificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NotificationPanelLayout.createSequentialGroup()
                                .addGroup(NotificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scheduleTagJL)
                                    .addComponent(PTSOTagJL)
                                    .addComponent(photoTagJL)
                                    .addComponent(P2TagJL)
                                    .addComponent(previewTagJL)
                                    .addComponent(blurbTagJL))
                                .addGap(41, 41, 41)
                                .addGroup(NotificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(schedulerTagJT, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(photoTagJT, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(P2TagJT, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(previewTagJT, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(blurbTagJT, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PTSOTagJT, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(NotificationPanelLayout.createSequentialGroup()
                                .addComponent(GenerateSQLJB)
                                .addGap(29, 29, 29)
                                .addComponent(ResetFormJB))))
                    .addGroup(NotificationPanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(TagHeadingJL, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        NotificationPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {P2TagJT, PTSOTagJT, blurbTagJT, photoTagJT, previewTagJT, schedulerTagJT});

        NotificationPanelLayout.setVerticalGroup(
            NotificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NotificationPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(TagHeadingJL, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(NotificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schedulerTagJT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scheduleTagJL))
                .addGap(18, 18, 18)
                .addGroup(NotificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PTSOTagJT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PTSOTagJL))
                .addGap(18, 18, 18)
                .addGroup(NotificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(photoTagJT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(photoTagJL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NotificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P2TagJT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P2TagJL))
                .addGap(18, 18, 18)
                .addGroup(NotificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previewTagJT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previewTagJL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NotificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blurbTagJT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blurbTagJL))
                .addGap(20, 20, 20)
                .addGroup(NotificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenerateSQLJB)
                    .addComponent(ResetFormJB))
                .addContainerGap())
        );

        NotificationPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {P2TagJT, PTSOTagJT, blurbTagJT, photoTagJT, previewTagJT, schedulerTagJT});

        MainPanel.addTab("Notification", null, NotificationPanel, "Notification Query Generator Tag");
        NotificationPanel.getAccessibleContext().setAccessibleParent(MainPanel);

        javax.swing.GroupLayout PermissionPanelLayout = new javax.swing.GroupLayout(PermissionPanel);
        PermissionPanel.setLayout(PermissionPanelLayout);
        PermissionPanelLayout.setHorizontalGroup(
            PermissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );
        PermissionPanelLayout.setVerticalGroup(
            PermissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        MainPanel.addTab("Permission", PermissionPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        MainPanel.getAccessibleContext().setAccessibleName("");
        MainPanel.getAccessibleContext().setAccessibleParent(MainPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void schedulerTagJTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schedulerTagJTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schedulerTagJTActionPerformed

    private void ResetFormJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetFormJBActionPerformed
        // TODO add your handling code here:
         schedulerTagJT.setText("");
         PTSOTagJT.setText("");
         photoTagJT.setText("");
         previewTagJT.setText("");
         blurbTagJT.setText("");
         P2TagJT.setText("");         
    }//GEN-LAST:event_ResetFormJBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GettingTagPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GettingTagPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GettingTagPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GettingTagPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GettingTagPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenerateSQLJB;
    private javax.swing.JTabbedPane MainPanel;
    private javax.swing.JPanel NotificationPanel;
    private javax.swing.JLabel P2TagJL;
    private javax.swing.JTextField P2TagJT;
    private javax.swing.JLabel PTSOTagJL;
    private javax.swing.JTextField PTSOTagJT;
    private javax.swing.JPanel PermissionPanel;
    private javax.swing.JButton ResetFormJB;
    private javax.swing.JLabel TagHeadingJL;
    private javax.swing.JLabel blurbTagJL;
    private javax.swing.JTextField blurbTagJT;
    private javax.swing.JLabel photoTagJL;
    private javax.swing.JTextField photoTagJT;
    private javax.swing.JLabel previewTagJL;
    private javax.swing.JTextField previewTagJT;
    private javax.swing.JLabel scheduleTagJL;
    private javax.swing.JTextField schedulerTagJT;
    // End of variables declaration//GEN-END:variables
}
